version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./test.Dockerfile
    command: poetry run pytest
    depends_on:
      - postgres_db
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    tty: true
    stdin_open: true

  postgres_db:
    image: postgres:14-alpine
    env_file:
      - .env
    ports:
      - '6543:5432'
